### ISSUE TITLE
Install.sh asking for password

### ISSUE THREAD

**Issue by Delocalized-electron** [VishnuNarayananSR/frescoplay-learning-app-MERN-stack#1]
While running install.sh, 
getting this output.

Node.js v18.16.0
Mongodb setup is done
Password:   <----- where its asking for password

**Comment by VishnuNarayananSR** [comment]
> While running install.sh, getting this output.
> 
> Node.js v18.16.0 Mongodb setup is done Password: <----- where its asking for password

Where are you running it? The script is written for hackerrank platform where you won't be prompted for password.
If you're trying to run in your local, you can comment the following line in install.sh
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

If you're interested to know what this line does:

It appends the line fs.inotify.max_user_watches=524288 to the /etc/sysctl.conf file using sudo and tee. It then uses sudo sysctl -p to apply changes made to the system's inotify settings by reloading the sysctl configuration.
Typically used to increase the maximum number of watches that a user can create using inotify in servers.

Hope that helps:)

**Comment by Delocalized-electron** [comment]
Yes, It helped Thank you!
